package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Artiste generated by hbm2java
 */
public class Artiste implements java.io.Serializable {

	private int numArtiste;
	private String nomArtiste;
	private Set spectacles = new HashSet(0);

	public Artiste() {
	}

	public Artiste(int numArtiste, String nomArtiste) {
		this.numArtiste = numArtiste;
		this.nomArtiste = nomArtiste;
	}

	public Artiste(int numArtiste, String nomArtiste, Set spectacles) {
		this.numArtiste = numArtiste;
		this.nomArtiste = nomArtiste;
		this.spectacles = spectacles;
	}

	public int getNumArtiste() {
		return this.numArtiste;
	}

	public void setNumArtiste(int numArtiste) {
		this.numArtiste = numArtiste;
	}

	public String getNomArtiste() {
		return this.nomArtiste;
	}

	public void setNomArtiste(String nomArtiste) {
		this.nomArtiste = nomArtiste;
	}

	public Set getSpectacles() {
		return this.spectacles;
	}

	public void setSpectacles(Set spectacles) {
		this.spectacles = spectacles;
	}

}
