package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

/**
 * Avoir generated by hbm2java
 */
public class Avoir implements java.io.Serializable {

	private AvoirId id;
	private Spectacle spectacle;

	public Avoir() {
	}

	public Avoir(AvoirId id, Spectacle spectacle) {
		this.id = id;
		this.spectacle = spectacle;
	}

	public AvoirId getId() {
		return this.id;
	}

	public void setId(AvoirId id) {
		this.id = id;
	}

	public Spectacle getSpectacle() {
		return this.spectacle;
	}

	public void setSpectacle(Spectacle spectacle) {
		this.spectacle = spectacle;
	}

}
