package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

/**
 * BilletSpectacleId generated by hbm2java
 */
public class BilletSpectacleId implements java.io.Serializable {

	private int numSpect;
	private int numRepresentation;
	private int numBillet;

	public BilletSpectacleId() {
	}

	public BilletSpectacleId(int numSpect, int numRepresentation, int numBillet) {
		this.numSpect = numSpect;
		this.numRepresentation = numRepresentation;
		this.numBillet = numBillet;
	}

	public int getNumSpect() {
		return this.numSpect;
	}

	public void setNumSpect(int numSpect) {
		this.numSpect = numSpect;
	}

	public int getNumRepresentation() {
		return this.numRepresentation;
	}

	public void setNumRepresentation(int numRepresentation) {
		this.numRepresentation = numRepresentation;
	}

	public int getNumBillet() {
		return this.numBillet;
	}

	public void setNumBillet(int numBillet) {
		this.numBillet = numBillet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BilletSpectacleId))
			return false;
		BilletSpectacleId castOther = (BilletSpectacleId) other;

		return (this.getNumSpect() == castOther.getNumSpect())
				&& (this.getNumRepresentation() == castOther
						.getNumRepresentation())
				&& (this.getNumBillet() == castOther.getNumBillet());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumSpect();
		result = 37 * result + this.getNumRepresentation();
		result = 37 * result + this.getNumBillet();
		return result;
	}

}
