package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * BilletSpectacle generated by hbm2java
 */
public class BilletSpectacle implements java.io.Serializable {

	private BilletSpectacleId id;
	private Reservation reservation;
	private Position position;
	private Representation representation;
	private CategorieSpectateurTarif categorieSpectateurTarif;
	private PlaceAssise placeAssise;
	private CategoriePlace categoriePlace;
	private BigDecimal prix;

	public BilletSpectacle() {
	}

	public BilletSpectacle(BilletSpectacleId id, Reservation reservation,
			Position position, Representation representation,
			CategorieSpectateurTarif categorieSpectateurTarif,
			PlaceAssise placeAssise, CategoriePlace categoriePlace,
			BigDecimal prix) {
		this.id = id;
		this.reservation = reservation;
		this.position = position;
		this.representation = representation;
		this.categorieSpectateurTarif = categorieSpectateurTarif;
		this.placeAssise = placeAssise;
		this.categoriePlace = categoriePlace;
		this.prix = prix;
	}

	public BilletSpectacleId getId() {
		return this.id;
	}

	public void setId(BilletSpectacleId id) {
		this.id = id;
	}

	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public Representation getRepresentation() {
		return this.representation;
	}

	public void setRepresentation(Representation representation) {
		this.representation = representation;
	}

	public CategorieSpectateurTarif getCategorieSpectateurTarif() {
		return this.categorieSpectateurTarif;
	}

	public void setCategorieSpectateurTarif(
			CategorieSpectateurTarif categorieSpectateurTarif) {
		this.categorieSpectateurTarif = categorieSpectateurTarif;
	}

	public PlaceAssise getPlaceAssise() {
		return this.placeAssise;
	}

	public void setPlaceAssise(PlaceAssise placeAssise) {
		this.placeAssise = placeAssise;
	}

	public CategoriePlace getCategoriePlace() {
		return this.categoriePlace;
	}

	public void setCategoriePlace(CategoriePlace categoriePlace) {
		this.categoriePlace = categoriePlace;
	}

	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

}
