package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CategorieSpectateurTarif generated by hbm2java
 */
public class CategorieSpectateurTarif implements java.io.Serializable {

	private String libCatSpect;
	private Set tarifers = new HashSet(0);
	private Set billetSpectacles = new HashSet(0);

	public CategorieSpectateurTarif() {
	}

	public CategorieSpectateurTarif(String libCatSpect) {
		this.libCatSpect = libCatSpect;
	}

	public CategorieSpectateurTarif(String libCatSpect, Set tarifers,
			Set billetSpectacles) {
		this.libCatSpect = libCatSpect;
		this.tarifers = tarifers;
		this.billetSpectacles = billetSpectacles;
	}

	public String getLibCatSpect() {
		return this.libCatSpect;
	}

	public void setLibCatSpect(String libCatSpect) {
		this.libCatSpect = libCatSpect;
	}

	public Set getTarifers() {
		return this.tarifers;
	}

	public void setTarifers(Set tarifers) {
		this.tarifers = tarifers;
	}

	public Set getBilletSpectacles() {
		return this.billetSpectacles;
	}

	public void setBilletSpectacles(Set billetSpectacles) {
		this.billetSpectacles = billetSpectacles;
	}

}
