package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriePlace generated by hbm2java
 */
public class CategoriePlace implements java.io.Serializable {

	private String libCat;
	private Set tarifers = new HashSet(0);
	private Set configurers = new HashSet(0);
	private Set configurerLibres = new HashSet(0);
	private Set billetSpectacles = new HashSet(0);

	public CategoriePlace() {
	}

	public CategoriePlace(String libCat) {
		this.libCat = libCat;
	}

	public CategoriePlace(String libCat, Set tarifers, Set configurers,
			Set configurerLibres, Set billetSpectacles) {
		this.libCat = libCat;
		this.tarifers = tarifers;
		this.configurers = configurers;
		this.configurerLibres = configurerLibres;
		this.billetSpectacles = billetSpectacles;
	}

	public String getLibCat() {
		return this.libCat;
	}

	public void setLibCat(String libCat) {
		this.libCat = libCat;
	}

	public Set getTarifers() {
		return this.tarifers;
	}

	public void setTarifers(Set tarifers) {
		this.tarifers = tarifers;
	}

	public Set getConfigurers() {
		return this.configurers;
	}

	public void setConfigurers(Set configurers) {
		this.configurers = configurers;
	}

	public Set getConfigurerLibres() {
		return this.configurerLibres;
	}

	public void setConfigurerLibres(Set configurerLibres) {
		this.configurerLibres = configurerLibres;
	}

	public Set getBilletSpectacles() {
		return this.billetSpectacles;
	}

	public void setBilletSpectacles(Set billetSpectacles) {
		this.billetSpectacles = billetSpectacles;
	}

}
