package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CategorieSpectacle generated by hbm2java
 */
public class CategorieSpectacle implements java.io.Serializable {

	private String nomCat;
	private Set spectacles = new HashSet(0);

	public CategorieSpectacle() {
	}

	public CategorieSpectacle(String nomCat) {
		this.nomCat = nomCat;
	}

	public CategorieSpectacle(String nomCat, Set spectacles) {
		this.nomCat = nomCat;
		this.spectacles = spectacles;
	}

	public String getNomCat() {
		return this.nomCat;
	}

	public void setNomCat(String nomCat) {
		this.nomCat = nomCat;
	}

	public Set getSpectacles() {
		return this.spectacles;
	}

	public void setSpectacles(Set spectacles) {
		this.spectacles = spectacles;
	}

}
