package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

/**
 * Configurer generated by hbm2java
 */
public class Configurer implements java.io.Serializable {

	private ConfigurerId id;
	private SalleConfiguree salleConfiguree;
	private PlaceAssise placeAssise;
	private CategoriePlace categoriePlace;

	public Configurer() {
	}

	public Configurer(ConfigurerId id, SalleConfiguree salleConfiguree,
			PlaceAssise placeAssise, CategoriePlace categoriePlace) {
		this.id = id;
		this.salleConfiguree = salleConfiguree;
		this.placeAssise = placeAssise;
		this.categoriePlace = categoriePlace;
	}

	public ConfigurerId getId() {
		return this.id;
	}

	public void setId(ConfigurerId id) {
		this.id = id;
	}

	public SalleConfiguree getSalleConfiguree() {
		return this.salleConfiguree;
	}

	public void setSalleConfiguree(SalleConfiguree salleConfiguree) {
		this.salleConfiguree = salleConfiguree;
	}

	public PlaceAssise getPlaceAssise() {
		return this.placeAssise;
	}

	public void setPlaceAssise(PlaceAssise placeAssise) {
		this.placeAssise = placeAssise;
	}

	public CategoriePlace getCategoriePlace() {
		return this.categoriePlace;
	}

	public void setCategoriePlace(CategoriePlace categoriePlace) {
		this.categoriePlace = categoriePlace;
	}

}
