package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

/**
 * ConfigurerLibre generated by hbm2java
 */
public class ConfigurerLibre implements java.io.Serializable {

	private ConfigurerLibreId id;
	private Position position;
	private SalleConfiguree salleConfiguree;
	private CategoriePlace categoriePlace;

	public ConfigurerLibre() {
	}

	public ConfigurerLibre(ConfigurerLibreId id, Position position,
			SalleConfiguree salleConfiguree, CategoriePlace categoriePlace) {
		this.id = id;
		this.position = position;
		this.salleConfiguree = salleConfiguree;
		this.categoriePlace = categoriePlace;
	}

	public ConfigurerLibreId getId() {
		return this.id;
	}

	public void setId(ConfigurerLibreId id) {
		this.id = id;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public SalleConfiguree getSalleConfiguree() {
		return this.salleConfiguree;
	}

	public void setSalleConfiguree(SalleConfiguree salleConfiguree) {
		this.salleConfiguree = salleConfiguree;
	}

	public CategoriePlace getCategoriePlace() {
		return this.categoriePlace;
	}

	public void setCategoriePlace(CategoriePlace categoriePlace) {
		this.categoriePlace = categoriePlace;
	}

}
