package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DemoProductInfo generated by hbm2java
 */
public class DemoProductInfo implements java.io.Serializable {

	private BigDecimal productId;
	private String productName;
	private String productDescription;
	private String category;
	private String productAvail;
	private BigDecimal listPrice;
	private Blob productImage;
	private String mimetype;
	private String filename;
	private Date imageLastUpdate;
	private Set demoOrderItemses = new HashSet(0);

	public DemoProductInfo() {
	}

	public DemoProductInfo(BigDecimal productId) {
		this.productId = productId;
	}

	public DemoProductInfo(BigDecimal productId, String productName,
			String productDescription, String category, String productAvail,
			BigDecimal listPrice, Blob productImage, String mimetype,
			String filename, Date imageLastUpdate, Set demoOrderItemses) {
		this.productId = productId;
		this.productName = productName;
		this.productDescription = productDescription;
		this.category = category;
		this.productAvail = productAvail;
		this.listPrice = listPrice;
		this.productImage = productImage;
		this.mimetype = mimetype;
		this.filename = filename;
		this.imageLastUpdate = imageLastUpdate;
		this.demoOrderItemses = demoOrderItemses;
	}

	public BigDecimal getProductId() {
		return this.productId;
	}

	public void setProductId(BigDecimal productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getProductAvail() {
		return this.productAvail;
	}

	public void setProductAvail(String productAvail) {
		this.productAvail = productAvail;
	}

	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public Blob getProductImage() {
		return this.productImage;
	}

	public void setProductImage(Blob productImage) {
		this.productImage = productImage;
	}

	public String getMimetype() {
		return this.mimetype;
	}

	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Date getImageLastUpdate() {
		return this.imageLastUpdate;
	}

	public void setImageLastUpdate(Date imageLastUpdate) {
		this.imageLastUpdate = imageLastUpdate;
	}

	public Set getDemoOrderItemses() {
		return this.demoOrderItemses;
	}

	public void setDemoOrderItemses(Set demoOrderItemses) {
		this.demoOrderItemses = demoOrderItemses;
	}

}
