package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * DemoOrderItems generated by hbm2java
 */
public class DemoOrderItems implements java.io.Serializable {

	private short orderItemId;
	private DemoProductInfo demoProductInfo;
	private DemoOrders demoOrders;
	private BigDecimal unitPrice;
	private int quantity;

	public DemoOrderItems() {
	}

	public DemoOrderItems(short orderItemId, DemoProductInfo demoProductInfo,
			DemoOrders demoOrders, BigDecimal unitPrice, int quantity) {
		this.orderItemId = orderItemId;
		this.demoProductInfo = demoProductInfo;
		this.demoOrders = demoOrders;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
	}

	public short getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(short orderItemId) {
		this.orderItemId = orderItemId;
	}

	public DemoProductInfo getDemoProductInfo() {
		return this.demoProductInfo;
	}

	public void setDemoProductInfo(DemoProductInfo demoProductInfo) {
		this.demoProductInfo = demoProductInfo;
	}

	public DemoOrders getDemoOrders() {
		return this.demoOrders;
	}

	public void setDemoOrders(DemoOrders demoOrders) {
		this.demoOrders = demoOrders;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
