package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

/**
 * DemoStates generated by hbm2java
 */
public class DemoStates implements java.io.Serializable {

	private DemoStatesId id;

	public DemoStates() {
	}

	public DemoStates(DemoStatesId id) {
		this.id = id;
	}

	public DemoStatesId getId() {
		return this.id;
	}

	public void setId(DemoStatesId id) {
		this.id = id;
	}

}
