package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DemoCustomers generated by hbm2java
 */
public class DemoCustomers implements java.io.Serializable {

	private BigDecimal customerId;
	private String custFirstName;
	private String custLastName;
	private String custStreetAddress1;
	private String custStreetAddress2;
	private String custCity;
	private String custState;
	private String custPostalCode;
	private String phoneNumber1;
	private String phoneNumber2;
	private BigDecimal creditLimit;
	private String custEmail;
	private Set demoOrderses = new HashSet(0);

	public DemoCustomers() {
	}

	public DemoCustomers(BigDecimal customerId, String custFirstName,
			String custLastName) {
		this.customerId = customerId;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
	}

	public DemoCustomers(BigDecimal customerId, String custFirstName,
			String custLastName, String custStreetAddress1,
			String custStreetAddress2, String custCity, String custState,
			String custPostalCode, String phoneNumber1, String phoneNumber2,
			BigDecimal creditLimit, String custEmail, Set demoOrderses) {
		this.customerId = customerId;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.custStreetAddress1 = custStreetAddress1;
		this.custStreetAddress2 = custStreetAddress2;
		this.custCity = custCity;
		this.custState = custState;
		this.custPostalCode = custPostalCode;
		this.phoneNumber1 = phoneNumber1;
		this.phoneNumber2 = phoneNumber2;
		this.creditLimit = creditLimit;
		this.custEmail = custEmail;
		this.demoOrderses = demoOrderses;
	}

	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	public String getCustFirstName() {
		return this.custFirstName;
	}

	public void setCustFirstName(String custFirstName) {
		this.custFirstName = custFirstName;
	}

	public String getCustLastName() {
		return this.custLastName;
	}

	public void setCustLastName(String custLastName) {
		this.custLastName = custLastName;
	}

	public String getCustStreetAddress1() {
		return this.custStreetAddress1;
	}

	public void setCustStreetAddress1(String custStreetAddress1) {
		this.custStreetAddress1 = custStreetAddress1;
	}

	public String getCustStreetAddress2() {
		return this.custStreetAddress2;
	}

	public void setCustStreetAddress2(String custStreetAddress2) {
		this.custStreetAddress2 = custStreetAddress2;
	}

	public String getCustCity() {
		return this.custCity;
	}

	public void setCustCity(String custCity) {
		this.custCity = custCity;
	}

	public String getCustState() {
		return this.custState;
	}

	public void setCustState(String custState) {
		this.custState = custState;
	}

	public String getCustPostalCode() {
		return this.custPostalCode;
	}

	public void setCustPostalCode(String custPostalCode) {
		this.custPostalCode = custPostalCode;
	}

	public String getPhoneNumber1() {
		return this.phoneNumber1;
	}

	public void setPhoneNumber1(String phoneNumber1) {
		this.phoneNumber1 = phoneNumber1;
	}

	public String getPhoneNumber2() {
		return this.phoneNumber2;
	}

	public void setPhoneNumber2(String phoneNumber2) {
		this.phoneNumber2 = phoneNumber2;
	}

	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	public Set getDemoOrderses() {
		return this.demoOrderses;
	}

	public void setDemoOrderses(Set demoOrderses) {
		this.demoOrderses = demoOrderses;
	}

}
