package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

	private String nomGenre;

	public Genre() {
	}

	public Genre(String nomGenre) {
		this.nomGenre = nomGenre;
	}

	public String getNomGenre() {
		return this.nomGenre;
	}

	public void setNomGenre(String nomGenre) {
		this.nomGenre = nomGenre;
	}

}
