package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PlaceAssise generated by hbm2java
 */
public class PlaceAssise implements java.io.Serializable {

	private PlaceAssiseId id;
	private Position position;
	private String bloc;
	private Set configurers = new HashSet(0);
	private Set billetSpectacles = new HashSet(0);

	public PlaceAssise() {
	}

	public PlaceAssise(PlaceAssiseId id, Position position) {
		this.id = id;
		this.position = position;
	}

	public PlaceAssise(PlaceAssiseId id, Position position, String bloc,
			Set configurers, Set billetSpectacles) {
		this.id = id;
		this.position = position;
		this.bloc = bloc;
		this.configurers = configurers;
		this.billetSpectacles = billetSpectacles;
	}

	public PlaceAssiseId getId() {
		return this.id;
	}

	public void setId(PlaceAssiseId id) {
		this.id = id;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getBloc() {
		return this.bloc;
	}

	public void setBloc(String bloc) {
		this.bloc = bloc;
	}

	public Set getConfigurers() {
		return this.configurers;
	}

	public void setConfigurers(Set configurers) {
		this.configurers = configurers;
	}

	public Set getBilletSpectacles() {
		return this.billetSpectacles;
	}

	public void setBilletSpectacles(Set billetSpectacles) {
		this.billetSpectacles = billetSpectacles;
	}

}
