package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

/**
 * PositionId generated by hbm2java
 */
public class PositionId implements java.io.Serializable {

	private int numSalle;
	private String nomPosition;

	public PositionId() {
	}

	public PositionId(int numSalle, String nomPosition) {
		this.numSalle = numSalle;
		this.nomPosition = nomPosition;
	}

	public int getNumSalle() {
		return this.numSalle;
	}

	public void setNumSalle(int numSalle) {
		this.numSalle = numSalle;
	}

	public String getNomPosition() {
		return this.nomPosition;
	}

	public void setNomPosition(String nomPosition) {
		this.nomPosition = nomPosition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PositionId))
			return false;
		PositionId castOther = (PositionId) other;

		return (this.getNumSalle() == castOther.getNumSalle())
				&& ((this.getNomPosition() == castOther.getNomPosition()) || (this
						.getNomPosition() != null
						&& castOther.getNomPosition() != null && this
						.getNomPosition().equals(castOther.getNomPosition())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumSalle();
		result = 37
				* result
				+ (getNomPosition() == null ? 0 : this.getNomPosition()
						.hashCode());
		return result;
	}

}
