package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Publicite generated by hbm2java
 */
public class Publicite implements java.io.Serializable {

	private int numPub;
	private Spectacle spectacle;
	private String nomPub;
	private Date dateDebutPub;
	private Date dateFinPub;

	public Publicite() {
	}

	public Publicite(int numPub, Spectacle spectacle, String nomPub,
			Date dateDebutPub, Date dateFinPub) {
		this.numPub = numPub;
		this.spectacle = spectacle;
		this.nomPub = nomPub;
		this.dateDebutPub = dateDebutPub;
		this.dateFinPub = dateFinPub;
	}

	public int getNumPub() {
		return this.numPub;
	}

	public void setNumPub(int numPub) {
		this.numPub = numPub;
	}

	public Spectacle getSpectacle() {
		return this.spectacle;
	}

	public void setSpectacle(Spectacle spectacle) {
		this.spectacle = spectacle;
	}

	public String getNomPub() {
		return this.nomPub;
	}

	public void setNomPub(String nomPub) {
		this.nomPub = nomPub;
	}

	public Date getDateDebutPub() {
		return this.dateDebutPub;
	}

	public void setDateDebutPub(Date dateDebutPub) {
		this.dateDebutPub = dateDebutPub;
	}

	public Date getDateFinPub() {
		return this.dateFinPub;
	}

	public void setDateFinPub(Date dateFinPub) {
		this.dateFinPub = dateFinPub;
	}

}
