package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

/**
 * RepresentationId generated by hbm2java
 */
public class RepresentationId implements java.io.Serializable {

	private int numSpect;
	private int numRepresentation;

	public RepresentationId() {
	}

	public RepresentationId(int numSpect, int numRepresentation) {
		this.numSpect = numSpect;
		this.numRepresentation = numRepresentation;
	}

	public int getNumSpect() {
		return this.numSpect;
	}

	public void setNumSpect(int numSpect) {
		this.numSpect = numSpect;
	}

	public int getNumRepresentation() {
		return this.numRepresentation;
	}

	public void setNumRepresentation(int numRepresentation) {
		this.numRepresentation = numRepresentation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepresentationId))
			return false;
		RepresentationId castOther = (RepresentationId) other;

		return (this.getNumSpect() == castOther.getNumSpect())
				&& (this.getNumRepresentation() == castOther
						.getNumRepresentation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumSpect();
		result = 37 * result + this.getNumRepresentation();
		return result;
	}

}
