package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Representation generated by hbm2java
 */
public class Representation implements java.io.Serializable {

	private RepresentationId id;
	private SalleConfiguree salleConfiguree;
	private Salle salle;
	private Spectacle spectacle;
	private Date dateRepresentation;
	private Date dateOuvertureReservation;
	private String nomSalle;
	private String nomSpectacle;
	private Set billetSpectacles = new HashSet(0);
	private Set tarifers = new HashSet(0);

	public Representation() {
	}

	public Representation(RepresentationId id, SalleConfiguree salleConfiguree,
			Salle salle, Spectacle spectacle, Date dateRepresentation,
			String nomSalle, String nomSpectacle) {
		this.id = id;
		this.salleConfiguree = salleConfiguree;
		this.salle = salle;
		this.spectacle = spectacle;
		this.dateRepresentation = dateRepresentation;
		this.nomSalle = nomSalle;
		this.nomSpectacle = nomSpectacle;
	}

	public Representation(RepresentationId id, SalleConfiguree salleConfiguree,
			Salle salle, Spectacle spectacle, Date dateRepresentation,
			Date dateOuvertureReservation, String nomSalle,
			String nomSpectacle, Set billetSpectacles, Set tarifers) {
		this.id = id;
		this.salleConfiguree = salleConfiguree;
		this.salle = salle;
		this.spectacle = spectacle;
		this.dateRepresentation = dateRepresentation;
		this.dateOuvertureReservation = dateOuvertureReservation;
		this.nomSalle = nomSalle;
		this.nomSpectacle = nomSpectacle;
		this.billetSpectacles = billetSpectacles;
		this.tarifers = tarifers;
	}

	public RepresentationId getId() {
		return this.id;
	}

	public void setId(RepresentationId id) {
		this.id = id;
	}

	public SalleConfiguree getSalleConfiguree() {
		return this.salleConfiguree;
	}

	public void setSalleConfiguree(SalleConfiguree salleConfiguree) {
		this.salleConfiguree = salleConfiguree;
	}

	public Salle getSalle() {
		return this.salle;
	}

	public void setSalle(Salle salle) {
		this.salle = salle;
	}

	public Spectacle getSpectacle() {
		return this.spectacle;
	}

	public void setSpectacle(Spectacle spectacle) {
		this.spectacle = spectacle;
	}

	public Date getDateRepresentation() {
		return this.dateRepresentation;
	}

	public void setDateRepresentation(Date dateRepresentation) {
		this.dateRepresentation = dateRepresentation;
	}

	public Date getDateOuvertureReservation() {
		return this.dateOuvertureReservation;
	}

	public void setDateOuvertureReservation(Date dateOuvertureReservation) {
		this.dateOuvertureReservation = dateOuvertureReservation;
	}

	public String getNomSalle() {
		return this.nomSalle;
	}

	public void setNomSalle(String nomSalle) {
		this.nomSalle = nomSalle;
	}

	public String getNomSpectacle() {
		return this.nomSpectacle;
	}

	public void setNomSpectacle(String nomSpectacle) {
		this.nomSpectacle = nomSpectacle;
	}

	public Set getBilletSpectacles() {
		return this.billetSpectacles;
	}

	public void setBilletSpectacles(Set billetSpectacles) {
		this.billetSpectacles = billetSpectacles;
	}

	public Set getTarifers() {
		return this.tarifers;
	}

	public void setTarifers(Set tarifers) {
		this.tarifers = tarifers;
	}

}
