package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private int numReservation;
	private Client client;
	private Date dateReservation;
	private BigDecimal montantFacture;
	private Long numTransaction;
	private Date dateTransaction;
	private Set billetSpectacles = new HashSet(0);

	public Reservation() {
	}

	public Reservation(int numReservation, Client client) {
		this.numReservation = numReservation;
		this.client = client;
	}

	public Reservation(int numReservation, Client client, Date dateReservation,
			BigDecimal montantFacture, Long numTransaction,
			Date dateTransaction, Set billetSpectacles) {
		this.numReservation = numReservation;
		this.client = client;
		this.dateReservation = dateReservation;
		this.montantFacture = montantFacture;
		this.numTransaction = numTransaction;
		this.dateTransaction = dateTransaction;
		this.billetSpectacles = billetSpectacles;
	}

	public int getNumReservation() {
		return this.numReservation;
	}

	public void setNumReservation(int numReservation) {
		this.numReservation = numReservation;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

	public BigDecimal getMontantFacture() {
		return this.montantFacture;
	}

	public void setMontantFacture(BigDecimal montantFacture) {
		this.montantFacture = montantFacture;
	}

	public Long getNumTransaction() {
		return this.numTransaction;
	}

	public void setNumTransaction(Long numTransaction) {
		this.numTransaction = numTransaction;
	}

	public Date getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(Date dateTransaction) {
		this.dateTransaction = dateTransaction;
	}

	public Set getBilletSpectacles() {
		return this.billetSpectacles;
	}

	public void setBilletSpectacles(Set billetSpectacles) {
		this.billetSpectacles = billetSpectacles;
	}

}
