package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

/**
 * SalleConfigure generated by hbm2java
 */
public class SalleConfigure implements java.io.Serializable {

	private int numConfig;
	private int numSalle;
	private String descConfig;

	public SalleConfigure() {
	}

	public SalleConfigure(int numConfig, int numSalle) {
		this.numConfig = numConfig;
		this.numSalle = numSalle;
	}

	public SalleConfigure(int numConfig, int numSalle, String descConfig) {
		this.numConfig = numConfig;
		this.numSalle = numSalle;
		this.descConfig = descConfig;
	}

	public int getNumConfig() {
		return this.numConfig;
	}

	public void setNumConfig(int numConfig) {
		this.numConfig = numConfig;
	}

	public int getNumSalle() {
		return this.numSalle;
	}

	public void setNumSalle(int numSalle) {
		this.numSalle = numSalle;
	}

	public String getDescConfig() {
		return this.descConfig;
	}

	public void setDescConfig(String descConfig) {
		this.descConfig = descConfig;
	}

}
