package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SalleConfiguree generated by hbm2java
 */
public class SalleConfiguree implements java.io.Serializable {

	private int numConfig;
	private Salle salle;
	private String descConfig;
	private Set representations = new HashSet(0);
	private Set configurerLibres = new HashSet(0);
	private Set configurers = new HashSet(0);
	private Set positions = new HashSet(0);

	public SalleConfiguree() {
	}

	public SalleConfiguree(int numConfig, Salle salle) {
		this.numConfig = numConfig;
		this.salle = salle;
	}

	public SalleConfiguree(int numConfig, Salle salle, String descConfig,
			Set representations, Set configurerLibres, Set configurers,
			Set positions) {
		this.numConfig = numConfig;
		this.salle = salle;
		this.descConfig = descConfig;
		this.representations = representations;
		this.configurerLibres = configurerLibres;
		this.configurers = configurers;
		this.positions = positions;
	}

	public int getNumConfig() {
		return this.numConfig;
	}

	public void setNumConfig(int numConfig) {
		this.numConfig = numConfig;
	}

	public Salle getSalle() {
		return this.salle;
	}

	public void setSalle(Salle salle) {
		this.salle = salle;
	}

	public String getDescConfig() {
		return this.descConfig;
	}

	public void setDescConfig(String descConfig) {
		this.descConfig = descConfig;
	}

	public Set getRepresentations() {
		return this.representations;
	}

	public void setRepresentations(Set representations) {
		this.representations = representations;
	}

	public Set getConfigurerLibres() {
		return this.configurerLibres;
	}

	public void setConfigurerLibres(Set configurerLibres) {
		this.configurerLibres = configurerLibres;
	}

	public Set getConfigurers() {
		return this.configurers;
	}

	public void setConfigurers(Set configurers) {
		this.configurers = configurers;
	}

	public Set getPositions() {
		return this.positions;
	}

	public void setPositions(Set positions) {
		this.positions = positions;
	}

}
