package fr.utbm.billetterie.models;

// Generated 26 mai 2012 16:34:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tarifer generated by hbm2java
 */
public class Tarifer implements java.io.Serializable {

	private TariferId id;
	private Representation representation;
	private CategorieSpectateurTarif categorieSpectateurTarif;
	private CategoriePlace categoriePlace;
	private BigDecimal prix;

	public Tarifer() {
	}

	public Tarifer(TariferId id, Representation representation,
			CategorieSpectateurTarif categorieSpectateurTarif,
			CategoriePlace categoriePlace, BigDecimal prix) {
		this.id = id;
		this.representation = representation;
		this.categorieSpectateurTarif = categorieSpectateurTarif;
		this.categoriePlace = categoriePlace;
		this.prix = prix;
	}

	public TariferId getId() {
		return this.id;
	}

	public void setId(TariferId id) {
		this.id = id;
	}

	public Representation getRepresentation() {
		return this.representation;
	}

	public void setRepresentation(Representation representation) {
		this.representation = representation;
	}

	public CategorieSpectateurTarif getCategorieSpectateurTarif() {
		return this.categorieSpectateurTarif;
	}

	public void setCategorieSpectateurTarif(
			CategorieSpectateurTarif categorieSpectateurTarif) {
		this.categorieSpectateurTarif = categorieSpectateurTarif;
	}

	public CategoriePlace getCategoriePlace() {
		return this.categoriePlace;
	}

	public void setCategoriePlace(CategoriePlace categoriePlace) {
		this.categoriePlace = categoriePlace;
	}

	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

}
