package fr.utbm.billetterie.models;

// Generated 26 mai 2012 13:57:02 by Hibernate Tools 3.4.0.CR1

/**
 * TariferId generated by hbm2java
 */
public class TariferId implements java.io.Serializable {

	private int numSpect;
	private int numRepresentation;
	private String libCat;
	private String libCatSpect;

	public TariferId() {
	}

	public TariferId(int numSpect, int numRepresentation, String libCat,
			String libCatSpect) {
		this.numSpect = numSpect;
		this.numRepresentation = numRepresentation;
		this.libCat = libCat;
		this.libCatSpect = libCatSpect;
	}

	public int getNumSpect() {
		return this.numSpect;
	}

	public void setNumSpect(int numSpect) {
		this.numSpect = numSpect;
	}

	public int getNumRepresentation() {
		return this.numRepresentation;
	}

	public void setNumRepresentation(int numRepresentation) {
		this.numRepresentation = numRepresentation;
	}

	public String getLibCat() {
		return this.libCat;
	}

	public void setLibCat(String libCat) {
		this.libCat = libCat;
	}

	public String getLibCatSpect() {
		return this.libCatSpect;
	}

	public void setLibCatSpect(String libCatSpect) {
		this.libCatSpect = libCatSpect;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TariferId))
			return false;
		TariferId castOther = (TariferId) other;

		return (this.getNumSpect() == castOther.getNumSpect())
				&& (this.getNumRepresentation() == castOther
						.getNumRepresentation())
				&& ((this.getLibCat() == castOther.getLibCat()) || (this
						.getLibCat() != null && castOther.getLibCat() != null && this
						.getLibCat().equals(castOther.getLibCat())))
				&& ((this.getLibCatSpect() == castOther.getLibCatSpect()) || (this
						.getLibCatSpect() != null
						&& castOther.getLibCatSpect() != null && this
						.getLibCatSpect().equals(castOther.getLibCatSpect())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumSpect();
		result = 37 * result + this.getNumRepresentation();
		result = 37 * result
				+ (getLibCat() == null ? 0 : this.getLibCat().hashCode());
		result = 37
				* result
				+ (getLibCatSpect() == null ? 0 : this.getLibCatSpect()
						.hashCode());
		return result;
	}

}
