
DROP TABLE CATEGORIE_PLACE CASCADE CONSTRAINTS;
DROP TABLE ARTISTE CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE_SPECTATEUR_TARIF CASCADE CONSTRAINTS;
DROP TABLE CONFIGURER CASCADE CONSTRAINTS;
DROP TABLE JOUER CASCADE CONSTRAINTS;
DROP TABLE CONFIGURER_NUMEROTE CASCADE CONSTRAINTS;
DROP TABLE TARIFER CASCADE CONSTRAINTS;
DROP TABLE AVOIR CASCADE CONSTRAINTS;
DROP TABLE CONFIGURER_LIBRE CASCADE CONSTRAINTS;

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_PLACE
-- -----------------------------------------------------------------------------

CREATE TABLE CATEGORIE_PLACE
   (
    LIB_CAT CHAR(12)  NOT NULL
,   CONSTRAINT PK_CATEGORIE_PLACE PRIMARY KEY (LIB_CAT)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : ARTISTE
-- -----------------------------------------------------------------------------

CREATE TABLE ARTISTE
   (
    NUM_ARTISTE NUMBER(6)  NOT NULL,
    NOM_ARTISTE VARCHAR2(25)  NOT NULL
,   CONSTRAINT PK_ARTISTE PRIMARY KEY (NUM_ARTISTE)  
   )
 ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_SPECTATEUR_TARIF
-- -----------------------------------------------------------------------------

CREATE TABLE CATEGORIE_SPECTATEUR_TARIF
   (
    LIB_CAT_SPECT CHAR(32)  NOT NULL
,   CONSTRAINT PK_CATEGORIE_SPECTATEUR_TARIF PRIMARY KEY (LIB_CAT_SPECT)  
   )
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER
-- -----------------------------------------------------------------------------

CREATE TABLE CONFIGURER
   (
    NUM_CONFIG NUMBER(6)  NOT NULL,
    NUM_SALLE NUMBER(6)  NOT NULL,
    NOM_POSITION VARCHAR2(25)  NOT NULL,
    NUM_PLACE NUMBER(6)  NOT NULL,
    RANG CHAR(3)  NOT NULL,
    LIB_CAT CHAR(12)  NOT NULL
,   CONSTRAINT PK_CONFIGURER PRIMARY KEY (NUM_CONFIG, NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : JOUER
-- -----------------------------------------------------------------------------

CREATE TABLE JOUER
   (
    NUM_SPECT NUMBER(6)  NOT NULL,
    NUM_ARTISTE NUMBER(6)  NOT NULL
,   CONSTRAINT PK_JOUER PRIMARY KEY (NUM_SPECT, NUM_ARTISTE)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_NUMEROTE
-- -----------------------------------------------------------------------------

CREATE TABLE CONFIGURER_NUMEROTE
   (
    NUM_CONFIG NUMBER(6)  NOT NULL,
    NUM_SALLE NUMBER(6)  NOT NULL,
    NOM_POSITION VARCHAR2(25)  NOT NULL
,   CONSTRAINT PK_CONFIGURER_NUMEROTE PRIMARY KEY (NUM_CONFIG, NUM_SALLE, NOM_POSITION)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : TARIFER
-- -----------------------------------------------------------------------------

CREATE TABLE TARIFER
   (
    NUM_SPECT NUMBER(6)  NOT NULL,
    NUM_REPRESENTATION NUMBER(6)  NOT NULL,
    LIB_CAT CHAR(12)  NOT NULL,
    LIB_CAT_SPECT CHAR(32)  NOT NULL,
    PRIX NUMBER(5,2)  NOT NULL
,   CONSTRAINT PK_TARIFER PRIMARY KEY (NUM_SPECT, NUM_REPRESENTATION, LIB_CAT, LIB_CAT_SPECT)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : AVOIR
-- -----------------------------------------------------------------------------

CREATE TABLE AVOIR
   (
    NOM_GENRE VARCHAR2(25)  NOT NULL,
    NUM_SPECT NUMBER(6)  NOT NULL
,   CONSTRAINT PK_AVOIR PRIMARY KEY (NOM_GENRE, NUM_SPECT)  
   ) 
ORGANIZATION INDEX;
-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_LIBRE
-- -----------------------------------------------------------------------------

CREATE TABLE CONFIGURER_LIBRE
   (
    NUM_CONFIG NUMBER(6)  NOT NULL,
    NUM_SALLE NUMBER(6)  NOT NULL,
    NOM_POSITION VARCHAR2(25)  NOT NULL,
    LIB_CAT CHAR(12)  NOT NULL
,   CONSTRAINT PK_CONFIGURER_LIBRE PRIMARY KEY (NUM_CONFIG, NUM_SALLE, NOM_POSITION, LIB_CAT)  
   )
ORGANIZATION INDEX;

-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------
ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_SALLE_CONFIGUREE
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_PLACE_ASSISE
          FOREIGN KEY (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG)
               REFERENCES PLACE_ASSISE (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG))   ;

ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_CATEGORIE_PLACE
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;

ALTER TABLE JOUER ADD (
     CONSTRAINT FK_JOUER_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE JOUER ADD (
     CONSTRAINT FK_JOUER_ARTISTE
          FOREIGN KEY (NUM_ARTISTE)
               REFERENCES ARTISTE (NUM_ARTISTE))   ;

ALTER TABLE CONFIGURER_NUMEROTE ADD (
     CONSTRAINT FK_CONFIGURER_NUMEROTE_SALLE_C
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER_NUMEROTE ADD (
     CONSTRAINT FK_CONFIGURER_NUMEROTE_POSITIO
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_CATEGORIE_PLACE
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_REPRESENTATION
          FOREIGN KEY (NUM_SPECT, NUM_REPRESENTATION)
               REFERENCES REPRESENTATION (NUM_SPECT, NUM_REPRESENTATION))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_CATEGORIE_SPECTATEU
          FOREIGN KEY (LIB_CAT_SPECT)
               REFERENCES CATEGORIE_SPECTATEUR_TARIF (LIB_CAT_SPECT))   ;

ALTER TABLE AVOIR ADD (
     CONSTRAINT FK_AVOIR_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_SALLE_CONF
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_POSITION
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_CATEGORIE_
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;
