-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------


ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_RESERVATIO
          FOREIGN KEY (NUM_RESERVATION)
               REFERENCES RESERVATION (NUM_RESERVATION))   ;

ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_REPRESENTA
          FOREIGN KEY (NUM_SPECT, NUM_REPRESENTATION)
               REFERENCES REPRESENTATION (NUM_SPECT, NUM_REPRESENTATION))   ;

ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_CATEGORIE_
          FOREIGN KEY (LIB_CAT_SPECT)
               REFERENCES CATEGORIE_SPECTATEUR_TARIF (LIB_CAT_SPECT))   ;

ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_CATEGORIE1
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;

ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_POSITION
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE BILLET_SPECTACLE ADD (
     CONSTRAINT FK_BILLET_SPECTACLE_PLACE_ASSI
          FOREIGN KEY (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG)
               REFERENCES PLACE_ASSISE (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG))   ;

ALTER TABLE REPRESENTATION ADD (
     CONSTRAINT FK_REPRESENTATION_SALLE_CONFIG
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE REPRESENTATION ADD (
     CONSTRAINT FK_REPRESENTATION_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE REPRESENTATION ADD (
     CONSTRAINT FK_REPRESENTATION_SALLE
          FOREIGN KEY (NUM_SALLE)
               REFERENCES SALLE (NUM_SALLE))   ;

ALTER TABLE PLACE_ASSISE ADD (
     CONSTRAINT FK_PLACE_ASSISE_POSITION
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE PUBLICITE ADD (
     CONSTRAINT FK_PUBLICITE_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE RESERVATION ADD (
     CONSTRAINT FK_RESERVATION_CLIENT
          FOREIGN KEY (EMAIL_CLIENT)
               REFERENCES CLIENT (EMAIL_CLIENT))   ;

ALTER TABLE POSITION ADD (
     CONSTRAINT FK_POSITION_SALLE
          FOREIGN KEY (NUM_SALLE)
               REFERENCES SALLE (NUM_SALLE))   ;

ALTER TABLE SALLE_CONFIGUREE ADD (
     CONSTRAINT FK_SALLE_CONFIGUREE_SALLE
          FOREIGN KEY (NUM_SALLE)
               REFERENCES SALLE (NUM_SALLE))   ;

ALTER TABLE SALLE ADD (
     CONSTRAINT FK_SALLE_REGION
          FOREIGN KEY (NOM_REGION)
               REFERENCES REGION (NOM_REGION))   ;

ALTER TABLE SPECTACLE ADD (
     CONSTRAINT FK_SPECTACLE_CATEGORIE_SPECTAC
          FOREIGN KEY (NOM_CAT)
               REFERENCES CATEGORIE_SPECTACLE (NOM_CAT))   ;

ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_SALLE_CONFIGUREE
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_PLACE_ASSISE
          FOREIGN KEY (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG)
               REFERENCES PLACE_ASSISE (NUM_SALLE, NOM_POSITION, NUM_PLACE, RANG))   ;

ALTER TABLE CONFIGURER ADD (
     CONSTRAINT FK_CONFIGURER_CATEGORIE_PLACE
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;

ALTER TABLE JOUER ADD (
     CONSTRAINT FK_JOUER_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE JOUER ADD (
     CONSTRAINT FK_JOUER_ARTISTE
          FOREIGN KEY (NUM_ARTISTE)
               REFERENCES ARTISTE (NUM_ARTISTE))   ;

ALTER TABLE CONFIGURER_NUMEROTE ADD (
     CONSTRAINT FK_CONFIGURER_NUMEROTE_SALLE_C
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER_NUMEROTE ADD (
     CONSTRAINT FK_CONFIGURER_NUMEROTE_POSITIO
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_CATEGORIE_PLACE
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_REPRESENTATION
          FOREIGN KEY (NUM_SPECT, NUM_REPRESENTATION)
               REFERENCES REPRESENTATION (NUM_SPECT, NUM_REPRESENTATION))   ;

ALTER TABLE TARIFER ADD (
     CONSTRAINT FK_TARIFER_CATEGORIE_SPECTATEU
          FOREIGN KEY (LIB_CAT_SPECT)
               REFERENCES CATEGORIE_SPECTATEUR_TARIF (LIB_CAT_SPECT))   ;

ALTER TABLE AVOIR ADD (
     CONSTRAINT FK_AVOIR_SPECTACLE
          FOREIGN KEY (NUM_SPECT)
               REFERENCES SPECTACLE (NUM_SPECT))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_SALLE_CONF
          FOREIGN KEY (NUM_CONFIG)
               REFERENCES SALLE_CONFIGUREE (NUM_CONFIG))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_POSITION
          FOREIGN KEY (NUM_SALLE, NOM_POSITION)
               REFERENCES POSITION (NUM_SALLE, NOM_POSITION))   ;

ALTER TABLE CONFIGURER_LIBRE ADD (
     CONSTRAINT FK_CONFIGURER_LIBRE_CATEGORIE_
          FOREIGN KEY (LIB_CAT)
               REFERENCES CATEGORIE_PLACE (LIB_CAT))   ;