DROP TABLE BILLET_SPECTACLE CASCADE CONSTRAINTS;

DROP TABLE REGION CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE_SPECTACLE CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE_PLACE CASCADE CONSTRAINTS;

DROP TABLE ARTISTE CASCADE CONSTRAINTS;

DROP TABLE REPRESENTATION CASCADE CONSTRAINTS;

DROP TABLE CLIENT CASCADE CONSTRAINTS;

DROP TABLE PLACE_ASSISE CASCADE CONSTRAINTS;

DROP TABLE PUBLICITE CASCADE CONSTRAINTS;

DROP TABLE RESERVATION CASCADE CONSTRAINTS;

DROP TABLE POSITION CASCADE CONSTRAINTS;

DROP TABLE SALLE_CONFIGUREE CASCADE CONSTRAINTS;

DROP TABLE SALLE CASCADE CONSTRAINTS;

DROP TABLE SPECTACLE CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE_SPECTATEUR_TARIF CASCADE CONSTRAINTS;

DROP TABLE CONFIGURER CASCADE CONSTRAINTS;

DROP TABLE JOUER CASCADE CONSTRAINTS;

DROP TABLE CONFIGURER_NUMEROTE CASCADE CONSTRAINTS;

DROP TABLE TARIFER CASCADE CONSTRAINTS;

DROP TABLE AVOIR CASCADE CONSTRAINTS;

DROP TABLE CONFIGURER_LIBRE CASCADE CONSTRAINTS;