<<<<<<< HEAD:insert.sql
DELETE FROM CONFIGURER;
DELETE FROM CONFIGURER_NUMEROTE;
DELETE FROM CONFIGURER_LIBRE;
DELETE FROM BILLET_SPECTACLE;
DELETE FROM PLACE_ASSISE;
DELETE FROM POSITION;
DELETE FROM TARIFER;
DELETE FROM REPRESENTATION;
DELETE FROM SALLE_CONFIGUREE;
DELETE FROM SALLE;
DELETE FROM JOUER;
DELETE FROM PUBLICITE;
DELETE FROM SPECTACLE;
DELETE FROM ARTISTE;
DELETE FROM CATEGORIE_SPECTATEUR_TARIF;
DELETE FROM GENRE;
DELETE FROM RESERVATION;
DELETE FROM CLIENT;
DELETE FROM REGION;
DELETE FROM CATEGORIE_SPECTACLE;
DELETE FROM CATEGORIE_PLACE;



-- -----------------------------------------------------------------------------
--       TABLE : REGION
-- -----------------------------------------------------------------------------

INSERT INTO REGION(NOM_REGION) VALUES('Ile de France / Paris');
INSERT INTO REGION(NOM_REGION) VALUES('Nord');
INSERT INTO REGION(NOM_REGION) VALUES('Est');
INSERT INTO REGION(NOM_REGION) VALUES('Centre');
INSERT INTO REGION(NOM_REGION) VALUES('Ouest');
INSERT INTO REGION(NOM_REGION) VALUES('Sud');

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Concert');
INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Spectacle');
INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Théâtre');

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_PLACE
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CARRE OR');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT1');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT2');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT3');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('UNIQUE');


-- -----------------------------------------------------------------------------
--       TABLE : SALLE
-- -----------------------------------------------------------------------------

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(1,'Nord','HOTEL CASINO BARRIERE',777,'Pont de Flandres',59777,'LILLE',1200,'Le théâtre de 
	l''Hôtel Casino Barrière d''une capacité de 1200 places, propose ainsi à son public de 
	profiter tout au long de l''année d''une programmation variée : humour, variété française 
	et internationale, jazz, cirque, comédie musicale...');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(2,'Est','AXONE',6,'rue du commandant rossel',25200,'MONTBELIARD',5000,
	'L''ensemble des partenaires de l''Aire Urbaine Belfort-Montbéliard-Héricourt-Delle 
	a confié à la Communauté d''Agglomération du Pays de Montbéliard, l''édification de 
	l''Axone, grand équipement culturel et sportif, à l''échelle de son territoire.');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(3,'Ile de France / Paris','PALAIS OMNISPORT DE PARIS BERCY',8,'bd de Bercy',75012,'PARIS',18000,
	'C''est en 1983 que la construction du Palais omnisports de paris Bercy s''achève, 
	dévoilant un ouvrage colossal et unique. La salle possède en effet jusqu''à 17 000 
	places dans sa capacité maximale. La conception architecturale du Palais omnisports 
	de paris Bercy permet une visibilité parfaite de chacune des places puisqu''il n''y 
	a aucun poteau porteur dans les gradins : une vraie prouesse technique ! L''extérieur
	 est lui parfaitement reconnaissable au premier coup d''oeil grâce à sa structure 
	 pyramidale et ses parois en pente recouvertes de pelouse.');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(4,'Sud','ARENES DE NIMES','Rd point des Arenes',30000,'NIMES',23000,
	'De la même forme ovale que le Colisée de Rome, l’amphithéâtre de Nîmes, 
	construit à la fin du Ier siècle après J.-C., est composé de deux niveaux 
	de soixante arcades superposées ainsi que d’un attique.  A l’époque antique, 
	plus de 23 000 personnes pouvaient prendre place sur les gradins des arènes 
	de Nîmes pour assister à des chasses ou à des combats d’animaux ou de gladiateurs. ');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,
	RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(5,'Centre','OPERA DE VICHY',1,'Rue du Casino',03200,'VICHY',1400,
	'Inaugurée en 1903, la salle de l''Opéra de Vichy, l''un des plus beaux Opéras d''Europe, 
	pur joyau de style Art nouveau, unique en France, se prête à toutes les manifestations 
	lyriques et chorégraphiques. Elle présente dans une harmonie or et ivoire, une 
	merveilleuse décoration de masques, de lyres, de visages et de fleurs. ');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(6,'Ouest','ZENITH NANTES METROPOLE','ZAC D''AR MOR',44800,'ST HERBLAIN',8500,
	'Le Zénith de Nantes, inauguré à la fin 2006, outre le fait d''être une très grande 
	salle, est capable d''accueillir des spectacles d''une qualité exceptionnelle, 
	notamment des grandes tournées nationales et internationales.
	Doté de 8500 places, le Zénith Nantes Métropole propose des concerts de variété 
	française et internationale, programme humoristes, spectacles musicaux, cirque, 
	spectacles de danse, manifestations pour jeune public...');

-- -----------------------------------------------------------------------------
--       TABLE : SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(1,'Spectacle','Le lac des signes','10/24/12','04/09/13');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(2,'Concert','Jonny Hallyday','07/26/12','12/22/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(3,'Concert','Lenny kravitz','07/05/12','08/09/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(4,'Concert','Lady Gaga','09/22/12','10/04/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(5,'Concert','Guns N''Roses','07/05/12','09/01/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(6,'Concert','Radiohead','07/10/12','10/16/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(7,'Spectacle','Florence Foresti','07/15/12','09/23/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(8,'Spectacle','Dracula','07/26/12','08/04/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(9,'Théâtre','Ils se re-aiment','07/23/12','06/07/13');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(10,'Théâtre','Les chevaliers du fiel','07/01/12','12/12/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(11,'Théâtre','Voca people','07/01/12','05/24/13');

-- -----------------------------------------------------------------------------
--       TABLE : ARTISTE
-- -----------------------------------------------------------------------------

INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(1,'Jonny Hallyday');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(2,'Lenny Kravitz');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(3,'Lady Gaga');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(4,'Axi Rose');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(5,'Thom Yorke');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(6,'Phil Selway');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(7,'Florence Foresti');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(8,'Marius Petipa');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(9,'Lev Ivanov');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(10,'Konstantin Sergueev');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(11,'Pitor Tchaikovski');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(12,'Ron Thal');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(13,'Tommy Stinson');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(14,'Frank Ferrer');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(15,'Jonny Greenwood');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(16,'Colin Greenwood');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(17,'Golan Yosef');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(18,'Nathalie Fauquette');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(19,'Gregory Deck');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(20,'Lola Ces');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(21,'Pierre Palmade');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(22,'Michele Laroque');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(23,'Eric Carriere');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(24,'Francis Ginibre');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(25,'Eyal Cohen');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(26,'Shimon Smith');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(27,'Moran Sofer');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(28,'Naama Levy');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(29,'Ofir Tal');
-- -----------------------------------------------------------------------------
--       TABLE : JOUER
-- -----------------------------------------------------------------------------

INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,8);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,9);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,10);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,11);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(2,1);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(3,2);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(4,3);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,4);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,12);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,13);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,14);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,5);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,15);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,16);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,6);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(7,7);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,17);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,18);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,19);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,20);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(9,21);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(9,22);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(10,23);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(10,24);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,25);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,26);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,27);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,28);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,29);

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_SPECTATEUR_TARIF
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('NORMAL');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('SENIOR');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('ETUDIANT');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('SPECIAL');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('PROMOTION WEB');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('REDUIT');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('FAMILLE');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('GROUPE');

-- -----------------------------------------------------------------------------
--       TABLE : SALLE_CONFIGUREE
-- -----------------------------------------------------------------------------

INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(1,1,'Utilisation des gradins: 950 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(2,1,'Utilisation des gradins et mezzanine: 1050 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(3,1,'1200 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(4,2,'Assis-debout: 3000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(5,2,'Assis-debout: 4000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(6,2,'Tout assis: 5000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(7,3,'17000 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(8,4,'23000 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(9,5,'1400 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(10,6,'8500 places libres');
-- -----------------------------------------------------------------------------
--       TABLE : GENRE
-- -----------------------------------------------------------------------------

INSERT INTO GENRE(NOM_GENRE) VALUES('ROCK');
INSERT INTO GENRE(NOM_GENRE) VALUES('BLUES');
INSERT INTO GENRE(NOM_GENRE) VALUES('JAZZ');
INSERT INTO GENRE(NOM_GENRE) VALUES('METAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('ELECTRO');
INSERT INTO GENRE(NOM_GENRE) VALUES('FUNK');
INSERT INTO GENRE(NOM_GENRE) VALUES('FOLK');
INSERT INTO GENRE(NOM_GENRE) VALUES('TECHNO');
INSERT INTO GENRE(NOM_GENRE) VALUES('POP');
INSERT INTO GENRE(NOM_GENRE) VALUES('PUNK');
INSERT INTO GENRE(NOM_GENRE) VALUES('R&B');
INSERT INTO GENRE(NOM_GENRE) VALUES('RAP');
INSERT INTO GENRE(NOM_GENRE) VALUES('REGGAE');
INSERT INTO GENRE(NOM_GENRE) VALUES('SKA');
INSERT INTO GENRE(NOM_GENRE) VALUES('DANSE');
INSERT INTO GENRE(NOM_GENRE) VALUES('FAMILIAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('SUR GLACE');
INSERT INTO GENRE(NOM_GENRE) VALUES('MUSIC-HALL');
INSERT INTO GENRE(NOM_GENRE) VALUES('HUMOUR');
INSERT INTO GENRE(NOM_GENRE) VALUES('MUSICAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('CLASSIC');
INSERT INTO GENRE(NOM_GENRE) VALUES('COMEDIE');
INSERT INTO GENRE(NOM_GENRE) VALUES('DRAME');
INSERT INTO GENRE(NOM_GENRE) VALUES('COM.MUSICALE');
INSERT INTO GENRE(NOM_GENRE) VALUES('COM.DRAMAT');
INSERT INTO GENRE(NOM_GENRE) VALUES('IMPRO');
INSERT INTO GENRE(NOM_GENRE) VALUES('ONE M/W SHOW');


-- -----------------------------------------------------------------------------
--       TABLE : CLIENT
-- -----------------------------------------------------------------------------

INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('toto@utbm.fr','Joker','Toto',12,
	'rue des plaisanteries',31000,'Toulouse','haha',0);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('ronan@utbm.fr','Potage','Ronan',123,
	'bd Anatole France',90000,'Belfort','sade',1);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('johan@utbm.fr','BoleBesancon','Johan',444,
	'rue de la residence',90000,'Belfort','johan',0);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('anais@utbm.fr','Brossas','Anais',700,
	'bd Anatole France',90000,'Belfort','anais',0);

-- -----------------------------------------------------------------------------
--       TABLE : PUBLICITE
-- -----------------------------------------------------------------------------

INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(1,1,'Pub le lac des signes','10/24/12','11/03/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(2,2,'Pub jonny hallyday','07/26/12','08/05/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(3,9,'Pub ils se re-aiment','07/19/12','07/25/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(4,7,'Pub florence foresti','06/11/12','06/30/12');

-- -----------------------------------------------------------------------------
--       TABLE : REPRESENTATION
-- -----------------------------------------------------------------------------

INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,1,1,1,'10/24/12','06/03/12','HOTEL CASINO BARRIERE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,2,5,2,'11/10/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,3,4,2,'11/12/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,4,4,2,'11/13/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,5,8,4,'12/10/12','06/03/12','ARENES DE NIMES','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,6,7,3,'07/26/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,7,7,3,'07/28/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,8,7,3,'08/12/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,9,7,3,'11/16/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,10,4,2,'07/05/12','05/02/12','AXONE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,11,6,2,'07/06/12','05/02/12','AXONE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,12,10,6,'07/10/12','05/02/12','ZENITH NANTES METROPOLE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,13,9,5,'08/09/12','05/02/12','OPERA DE VICHY','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(4,14,7,3,'09/22/12','01/01/12','PALAIS OMNISPORT DE PARIS BERCY','Lady Gaga');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(4,15,4,2,'10/04/12','01/01/12','AXONE','Lady Gaga');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(5,16,4,2,'07/06/12','02/01/12','AXONE','Guns N''Roses');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(5,17,10,6,'08/05/12','02/01/12','ZENITH NANTES METROPOLE','Guns N''Roses');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(6,18,4,2,'07/10/12','03/01/12','AXONE','Radiohead');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(6,19,10,6,'08/05/12','03/01/12','ZENITH NANTES METROPOLE','Radiohead');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(7,20,5,2,'07/06/12','02/01/12','AXONE','Florence Foresti');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(7,21,2,1,'08/05/12','02/01/12','HOTEL CASINO BARRIERE','Florence Foresti');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(8,22,4,2,'07/26/12','02/23/12','AXONE','Dracula');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(8,23,3,1,'08/02/12','02/23/12','HOTEL CASINO BARRIERE','Dracula');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(9,24,9,5,'07/23/12','02/05/12','OPERA DE VICHY','Ils se re-aiment');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(9,25,7,3,'01/04/13','02/05/12','PALAIS OMNISPORT DE PARIS BERCY','Ils se re-aiment');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(10,26,9,5,'07/01/12','02/05/12','OPERA DE VICHY','Les chevaliers du fiel');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(10,27,7,3,'08/04/12','02/05/12','PALAIS OMNISPORT DE PARIS BERCY','Les chevaliers du fiel');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(11,28,4,2,'07/01/12','05/05/12','AXONE','Voca people');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(11,29,1,1,'10/24/12','05/05/12','HOTEL CASINO BARRIERE','Voca people');

-- -----------------------------------------------------------------------------
--       TABLE : TARIFER
-- -----------------------------------------------------------------------------

INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT1','REDUIT',41.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT2','REDUIT',34.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,10,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,10,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,11,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,11,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT3','NORMAL',43.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,13,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,13,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT1','NORMAL',122.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CARRE OR','NORMAL',100.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT2','NORMAL',72.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT3','NORMAL',50.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT1','NORMAL',122.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CARRE OR','NORMAL',100.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT2','NORMAL',72.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT3','NORMAL',50.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT1','NORMAL',69.70);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT2','NORMAL',59.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT3','NORMAL',49.90);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT1','NORMAL',69.70);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT2','NORMAL',59.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT3','NORMAL',49.90);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,18,'CAT1','NORMAL',76.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,18,'CAT2','NORMAL',65.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT1','NORMAL',76.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT2','NORMAL',65.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT1','SPECIAL',66.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT2','SPECIAL',55.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT1','NORMAL',59.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CARRE OR','NORMAL',80.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,21,'CAT1','NORMAL',59.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,21,'CARRE OR','NORMAL',80.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CARRE OR','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','NORMAL',65.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','PROMOTION WEB',51.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','PROMOTION WEB',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','PROMOTION WEB',30.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','FAMILLE',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','FAMILLE',33.75);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','FAMILLE',23.75);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CARRE OR','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT1','NORMAL',65.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,24,'CAT1','NORMAL',55.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,24,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT1','NORMAL',58.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT2','NORMAL',48.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT3','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,26,'UNIQUE','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,27,'CARRE OR','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,27,'CAT1','NORMAL',30.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CARRE OR','NORMAL',44.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT1','NORMAL',38.50);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT2','NORMAL',33.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CARRE OR','GROUPE',39.60);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT1','GROUPE',35.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT2','GROUPE',28.60);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,29,'CAT1','NORMAL',44.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,29,'CAT2','NORMAL',40.00);

-- -----------------------------------------------------------------------------
--       TABLE : RESERVATION
-- -----------------------------------------------------------------------------

INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(1,'johan@utbm.fr','06/01/12',49.00,1,'06/01/12');
INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(2,'johan@utbm.fr','06/01/12',59.00,1,'06/01/12');
INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(3,'johan@utbm.fr','06/01/12',75.00,1,'06/01/12');
INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(4,'toto@utbm.fr','08/01/12',72.80,1,'08/01/12');
INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(5,'ronan@utbm.fr','07/01/12',100.30,1,'07/01/12');
INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) 
VALUES(6,'anais@utbm.fr','09/01/12',75.00,1,'09/01/12');

-- -----------------------------------------------------------------------------
--       TABLE : POSITION
-- -----------------------------------------------------------------------------

INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Gradins',0,950);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Mezzanine',0,100);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Balcon',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Gradins',0,1000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Tribunes',0,500);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Parterre',3500,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(3,'Gradins',0,14000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(3,'Fosse',4000,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(4,'Gradins',0,15000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(4,'Fosse',8000,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'2eme Balcon',0,200);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'loges 1er Balcon',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'1er Balcon',0,200);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'loges d''orchestre',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'Orchestre',0,700);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(6,'Gradins',0,4900);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(6,'Parterre',3600,0);

-- -----------------------------------------------------------------------------
--       TABLE : PLACE_ASSISE
-- -----------------------------------------------------------------------------

INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',004,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',005,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',006,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',007,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',008,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',009,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',004,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',005,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',006,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',001,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',002,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',003,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',004,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',005,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',006,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',007,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',008,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',009,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',010,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',011,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',012,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',013,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',014,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',015,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',003,'G','A');

-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_LIBRE
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(1,1,'Gradins','CARRE OR');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(1,1,'Mezzanine','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(1,1,'Balcon','CAT2');

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(4,2,'Gradins','CARRE OR');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(4,2,'Tribunes','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(4,2,'Tribunes','CAT2');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(4,2,'Tribunes','CAT3');

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(7,3,'Gradins','CARRE OR');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(7,3,'Gradins','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(7,3,'Gradins','CAT2');

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(8,4,'Gradins','CARRE OR');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(8,4,'Gradins','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(8,4,'Gradins','CAT2');

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'2eme Balcon','CAT3');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'1er Balcon','CAT3');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'1er Balcon','CAT2');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'loges 1er Balcon','CAT2');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'loges d''orchestre','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(9,5,'Orchestre','CARRE OR');

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(10,6,'Gradins','CARRE OR');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(10,6,'Gradins','CAT1');
INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) 
VALUES(10,6,'Gradins','CAT2');

-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Gradins',001,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Gradins',002,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Gradins',003,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Mezzanine',004,'M','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Mezzanine',005,'M','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Mezzanine',006,'M','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Balcon',007,'B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Balcon',008,'B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(1,1,'Balcon',009,'B','CAT2');

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Gradins',001,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Gradins',002,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Gradins',003,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Tribunes',004,'T','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Tribunes',005,'T','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(4,2,'Tribunes',006,'T','CAT3');

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(7,3,'Gradins',001,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(7,3,'Gradins',002,'G','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(7,3,'Gradins',003,'G','CAT2');

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(8,4,'Gradins',001,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(8,4,'Gradins',002,'G','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(8,4,'Gradins',003,'G','CAT2');

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'2eme Balcon',001,'2B','CAT3');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'2eme Balcon',002,'2B','CAT3');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'2eme Balcon',003,'2B','CAT3');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'1er Balcon',004,'1B','CAT3');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'1er Balcon',005,'1B','CAT3');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'1er Balcon',006,'1B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges 1er Balcon',007,'L1B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges 1er Balcon',008,'L1B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges 1er Balcon',009,'L1B','CAT2');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges d''orchestre',010,'LO','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges d''orchestre',011,'LO','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'loges d''orchestre',012,'LO','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'Orchestre',013,'O','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'Orchestre',014,'O','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(9,5,'Orchestre',015,'O','CARRE OR');

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(10,6,'Gradins',001,'G','CARRE OR');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(10,6,'Gradins',002,'G','CAT1');
INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) 
VALUES(10,6,'Gradins',003,'G','CAT2');

-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_NUMEROTE
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(1,1,'Gradins');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(1,1,'Mezzanine');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(1,1,'Balcon');

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(4,2,'Gradins');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(4,2,'Tribunes');

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(7,3,'Gradins');

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(8,4,'Gradins');

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(9,5,'2eme Balcon');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(9,5,'1er Balcon');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(9,5,'loges 1er Balcon');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(9,5,'loges d''orchestre');
INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(9,5,'Orchestre');

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) 
VALUES(10,6,'Gradins');

-- -----------------------------------------------------------------------------
--       TABLE : BILLET_SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO BILLET_SPECTACLE(NUM_SPECT,NUM_REPRESENTATION,NUM_BILLET,NUM_RESERVATION,
	LIB_CAT_SPECT,LIB_CAT,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,PRIX) 
VALUES(1,1,001,6,'NORMAL','CAT1',1,'Mezzanine',004,'M',45.00);

=======
DELETE FROM PLACE_ASSISE;
DELETE FROM POSITION;
DELETE FROM TARIFER;
DELETE FROM REPRESENTATION;
DELETE FROM SALLE_CONFIGUREE;
DELETE FROM SALLE;
DELETE FROM JOUER;
DELETE FROM PUBLICITE;
DELETE FROM SPECTACLE;
DELETE FROM ARTISTE;
DELETE FROM CATEGORIE_SPECTATEUR_TARIF;
DELETE FROM CONFIGURER;
DELETE FROM CONFIGURER_NUMEROTE;
DELETE FROM GENRE;
DELETE FROM CONFIGURER_LIBRE;
DELETE FROM CLIENT;
DELETE FROM RESERVATION;
DELETE FROM PLACE_ASSISE;
DELETE FROM BILLET_SPECTACLE;
DELETE FROM REGION;
DELETE FROM CATEGORIE_SPECTACLE;
DELETE FROM CATEGORIE_PLACE;



-- -----------------------------------------------------------------------------
--       TABLE : REGION
-- -----------------------------------------------------------------------------

INSERT INTO REGION(NOM_REGION) VALUES('Ile de France / Paris');
INSERT INTO REGION(NOM_REGION) VALUES('Nord');
INSERT INTO REGION(NOM_REGION) VALUES('Est');
INSERT INTO REGION(NOM_REGION) VALUES('Centre');
INSERT INTO REGION(NOM_REGION) VALUES('Ouest');
INSERT INTO REGION(NOM_REGION) VALUES('Sud');

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Concert');
INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Spectacle');
INSERT INTO CATEGORIE_SPECTACLE(NOM_CAT) VALUES('Théâtre');

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_PLACE
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CARRE OR');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT1');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT2');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('CAT3');
INSERT INTO CATEGORIE_PLACE(LIB_CAT) VALUES('UNIQUE');


-- -----------------------------------------------------------------------------
--       TABLE : SALLE
-- -----------------------------------------------------------------------------

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(1,'Nord','HOTEL CASINO BARRIERE',777,'Pont de Flandres',59777,'LILLE',1200,'Le théâtre de 
	l''Hôtel Casino Barrière d''une capacité de 1200 places, propose ainsi à son public de 
	profiter tout au long de l''année d''une programmation variée : humour, variété française 
	et internationale, jazz, cirque, comédie musicale...');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(2,'Est','AXONE',6,'rue du commandant rossel',25200,'MONTBELIARD',5000,
	'L''ensemble des partenaires de l''Aire Urbaine Belfort-Montbéliard-Héricourt-Delle 
	a confié à la Communauté d''Agglomération du Pays de Montbéliard, l''édification de 
	l''Axone, grand équipement culturel et sportif, à l''échelle de son territoire.');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(3,'Ile de France / Paris','PALAIS OMNISPORT DE PARIS BERCY',8,'bd de Bercy',75012,'PARIS',18000,
	'C''est en 1983 que la construction du Palais omnisports de paris Bercy s''achève, 
	dévoilant un ouvrage colossal et unique. La salle possède en effet jusqu''à 17 000 
	places dans sa capacité maximale. La conception architecturale du Palais omnisports 
	de paris Bercy permet une visibilité parfaite de chacune des places puisqu''il n''y 
	a aucun poteau porteur dans les gradins : une vraie prouesse technique ! L''extérieur
	 est lui parfaitement reconnaissable au premier coup d''oeil grâce à sa structure 
	 pyramidale et ses parois en pente recouvertes de pelouse.');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(4,'Sud','ARENES DE NIMES','Rd point des Arenes',30000,'NIMES',23000,
	'De la même forme ovale que le Colisée de Rome, l’amphithéâtre de Nîmes, 
	construit à la fin du Ier siècle après J.-C., est composé de deux niveaux 
	de soixante arcades superposées ainsi que d’un attique.  A l’époque antique, 
	plus de 23 000 personnes pouvaient prendre place sur les gradins des arènes 
	de Nîmes pour assister à des chasses ou à des combats d’animaux ou de gladiateurs. ');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,NUMERO_RUE_SALLE,
	RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(5,'Centre','OPERA DE VICHY',1,'Rue du Casino',03200,'VICHY',1400,
	'Inaugurée en 1903, la salle de l''Opéra de Vichy, l''un des plus beaux Opéras d''Europe, 
	pur joyau de style Art nouveau, unique en France, se prête à toutes les manifestations 
	lyriques et chorégraphiques. Elle présente dans une harmonie or et ivoire, une 
	merveilleuse décoration de masques, de lyres, de visages et de fleurs. ');

INSERT INTO SALLE(NUM_SALLE,NOM_REGION,NOM_SALLE,RUE_SALLE,CP_SALLE,VILLE_SALLE,CAPACITE_MAX_SALLE,DESCRIPTION_SALLE) 
VALUES(6,'Ouest','ZENITH NANTES METROPOLE','ZAC D''AR MOR',44800,'ST HERBLAIN',8500,
	'Le Zénith de Nantes, inauguré à la fin 2006, outre le fait d''être une très grande 
	salle, est capable d''accueillir des spectacles d''une qualité exceptionnelle, 
	notamment des grandes tournées nationales et internationales.
	Doté de 8500 places, le Zénith Nantes Métropole propose des concerts de variété 
	française et internationale, programme humoristes, spectacles musicaux, cirque, 
	spectacles de danse, manifestations pour jeune public...');

-- -----------------------------------------------------------------------------
--       TABLE : SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(1,'Spectacle','Le lac des signes','10/24/12','04/09/13');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(2,'Concert','Jonny Hallyday','07/26/12','12/22/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(3,'Concert','Lenny kravitz','07/05/12','08/09/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(4,'Concert','Lady Gaga','09/22/12','10/04/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(5,'Concert','Guns N''Roses','07/05/12','09/01/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(6,'Concert','Radiohead','07/10/12','10/16/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(7,'Spectacle','Florence Foresti','07/15/12','09/23/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(8,'Spectacle','Dracula','07/26/12','08/04/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(9,'Théâtre','Ils se re-aiment','07/23/12','06/07/13');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(10,'Théâtre','Les chevaliers du fiel','07/01/12','12/12/12');
INSERT INTO SPECTACLE(NUM_SPECT,NOM_CAT,NOM_SPECT,DATE_DEBUT_SPECT,DATE_FIN_SPECT) 
VALUES(11,'Théâtre','Voca people','07/01/12','05/24/13');

-- -----------------------------------------------------------------------------
--       TABLE : ARTISTE
-- -----------------------------------------------------------------------------

INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(1,'Jonny Hallyday');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(2,'Lenny Kravitz');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(3,'Lady Gaga');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(4,'Axi Rose');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(5,'Thom Yorke');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(6,'Phil Selway');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(7,'Florence Foresti');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(8,'Marius Petipa');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(9,'Lev Ivanov');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(10,'Konstantin Sergueev');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(11,'Pitor Tchaikovski');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(12,'Ron Thal');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(13,'Tommy Stinson');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(14,'Frank Ferrer');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(15,'Jonny Greenwood');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(16,'Colin Greenwood');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(17,'Golan Yosef');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(18,'Nathalie Fauquette');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(19,'Gregory Deck');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(20,'Lola Ces');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(21,'Pierre Palmade');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(22,'Michele Laroque');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(23,'Eric Carriere');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(24,'Francis Ginibre');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(25,'Eyal Cohen');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(26,'Shimon Smith');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(27,'Moran Sofer');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(28,'Naama Levy');
INSERT INTO ARTISTE(NUM_ARTISTE,NOM_ARTISTE) VALUES(29,'Ofir Tal');
-- -----------------------------------------------------------------------------
--       TABLE : JOUER
-- -----------------------------------------------------------------------------

INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,8);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,9);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,10);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(1,11);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(2,1);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(3,2);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(4,3);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,4);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,12);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,13);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(5,14);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,5);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,15);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,16);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(6,6);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(7,7);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,17);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,18);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,19);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(8,20);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(9,21);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(9,22);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(10,23);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(10,24);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,25);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,26);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,27);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,28);
INSERT INTO JOUER(NUM_SPECT,NUM_ARTISTE) VALUES(11,29);

-- -----------------------------------------------------------------------------
--       TABLE : CATEGORIE_SPECTATEUR_TARIF
-- -----------------------------------------------------------------------------

INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('NORMAL');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('SENIOR');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('ETUDIANT');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('SPECIAL');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('PROMOTION WEB');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('REDUIT');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('FAMILLE');
INSERT INTO CATEGORIE_SPECTATEUR_TARIF(LIB_CAT_SPECT) VALUES('GROUPE');

-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER(NUM_CONFIG,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,LIB_CAT) VALUES();


-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_NUMEROTE
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER_NUMEROTE(NUM_CONFIG,NUM_SALLE,NOM_POSITION) VALUES();


-- -----------------------------------------------------------------------------
--       TABLE : SALLE_CONFIGUREE
-- -----------------------------------------------------------------------------

INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(1,1,'Utilisation des gradins: 950 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(2,1,'Utilisation des gradins et mezzanine: 1050 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(3,1,'1200 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(4,2,'Assis-debout: 3000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(5,2,'Assis-debout: 4000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(6,2,'Tout assis: 5000 places');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(7,3,'17000 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(8,4,'23000 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(9,5,'1400 places libres');
INSERT INTO SALLE_CONFIGUREE(NUM_CONFIG,NUM_SALLE,DESC_CONFIG) 
VALUES(10,6,'8500 places libres');
-- -----------------------------------------------------------------------------
--       TABLE : GENRE
-- -----------------------------------------------------------------------------

INSERT INTO GENRE(NOM_GENRE) VALUES('ROCK');
INSERT INTO GENRE(NOM_GENRE) VALUES('BLUES');
INSERT INTO GENRE(NOM_GENRE) VALUES('JAZZ');
INSERT INTO GENRE(NOM_GENRE) VALUES('METAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('ELECTRO');
INSERT INTO GENRE(NOM_GENRE) VALUES('FUNK');
INSERT INTO GENRE(NOM_GENRE) VALUES('FOLK');
INSERT INTO GENRE(NOM_GENRE) VALUES('TECHNO');
INSERT INTO GENRE(NOM_GENRE) VALUES('POP');
INSERT INTO GENRE(NOM_GENRE) VALUES('PUNK');
INSERT INTO GENRE(NOM_GENRE) VALUES('R&B');
INSERT INTO GENRE(NOM_GENRE) VALUES('RAP');
INSERT INTO GENRE(NOM_GENRE) VALUES('REGGAE');
INSERT INTO GENRE(NOM_GENRE) VALUES('SKA');
INSERT INTO GENRE(NOM_GENRE) VALUES('DANSE');
INSERT INTO GENRE(NOM_GENRE) VALUES('FAMILIAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('SUR GLACE');
INSERT INTO GENRE(NOM_GENRE) VALUES('MUSIC-HALL');
INSERT INTO GENRE(NOM_GENRE) VALUES('HUMOUR');
INSERT INTO GENRE(NOM_GENRE) VALUES('MUSICAL');
INSERT INTO GENRE(NOM_GENRE) VALUES('CLASSIC');
INSERT INTO GENRE(NOM_GENRE) VALUES('COMEDIE');
INSERT INTO GENRE(NOM_GENRE) VALUES('DRAME');
INSERT INTO GENRE(NOM_GENRE) VALUES('COM.MUSICALE');
INSERT INTO GENRE(NOM_GENRE) VALUES('COM.DRAMAT');
INSERT INTO GENRE(NOM_GENRE) VALUES('IMPRO');
INSERT INTO GENRE(NOM_GENRE) VALUES('ONE M/W SHOW');

-- -----------------------------------------------------------------------------
--       TABLE : CONFIGURER_LIBRE
-- -----------------------------------------------------------------------------

INSERT INTO CONFIGURER_LIBRE(NUM_CONFIG,NUM_SALLE,NOM_POSITION,LIB_CAT) VALUES();

-- -----------------------------------------------------------------------------
--       TABLE : CLIENT
-- -----------------------------------------------------------------------------

INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('toto@utbm.fr','Joker','Toto',12,
	'rue des plaisanteries',31000,'Toulouse','haha',0);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('ronan@utbm.fr','Potage','Ronan',123,
	'bd Anatole France',90000,'Belfort','sade',1);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('johan@utbm.fr','BoleBesancon','Johan',444,
	'rue de la residence',90000,'Belfort','johan',0);
INSERT INTO CLIENT(EMAIL_CLIENT,NOM_CLIENT,PRENOM_CLIENT,
	NUM_RUE_CLIENT,RUE_CLIENT,CP_CLIENT,VILLE_CLIENT,
	PASSWORD,ADMINISTRATEUR) VALUES('anais@utbm.fr','Brossas','Anais',700,
	'bd Anatole France',90000,'Belfort','anais',0);

-- -----------------------------------------------------------------------------
--       TABLE : PUBLICITE
-- -----------------------------------------------------------------------------

INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(1,1,'Pub le lac des signes','10/24/12','11/03/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(2,2,'Pub jonny hallyday','07/26/12','08/05/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(3,9,'Pub ils se re-aiment','07/19/12','07/25/12');
INSERT INTO PUBLICITE(NUM_PUB,NUM_SPECT,NOM_PUB,DATE_DEBUT_PUB,DATE_FIN_PUB) 
VALUES(4,7,'Pub florence foresti','06/11/12','06/30/12');


-- -----------------------------------------------------------------------------
--       TABLE : REPRESENTATION
-- -----------------------------------------------------------------------------

INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,1,1,1,'10/24/12','06/03/12','HOTEL CASINO BARRIERE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,2,5,2,'11/10/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,3,4,2,'11/12/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,4,4,2,'11/13/12','06/03/12','AXONE','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(1,5,8,4,'12/10/12','06/03/12','ARENES DE NIMES','Le lac des signes');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,6,7,3,'07/26/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,7,7,3,'07/28/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,8,7,3,'08/12/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(2,9,7,3,'11/16/12','06/14/12','PALAIS OMNISPORT DE PARIS BERCY','Jonny Hallyday');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,10,4,2,'07/05/12','05/02/12','AXONE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,11,6,2,'07/06/12','05/02/12','AXONE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,12,10,6,'07/10/12','05/02/12','ZENITH NANTES METROPOLE','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(3,13,9,5,'08/09/12','05/02/12','OPERA DE VICHY','Lenny Kravitz');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(4,14,7,3,'09/22/12','01/01/12','PALAIS OMNISPORT DE PARIS BERCY','Lady Gaga');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(4,15,4,2,'10/04/12','01/01/12','AXONE','Lady Gaga');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(5,16,4,2,'07/06/12','02/01/12','AXONE','Guns N''Roses');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(5,17,10,6,'08/05/12','02/01/12','ZENITH NANTES METROPOLE','Guns N''Roses');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(6,18,4,2,'07/10/12','03/01/12','AXONE','Radiohead');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(6,19,10,6,'08/05/12','03/01/12','ZENITH NANTES METROPOLE','Radiohead');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(7,20,5,2,'07/06/12','02/01/12','AXONE','Florence Foresti');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(7,21,2,1,'08/05/12','02/01/12','HOTEL CASINO BARRIERE','Florence Foresti');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(8,22,4,2,'07/26/12','02/23/12','AXONE','Dracula');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(8,23,3,1,'08/02/12','02/23/12','HOTEL CASINO BARRIERE','Dracula');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(9,24,9,5,'07/23/12','02/05/12','OPERA DE VICHY','Ils se re-aiment');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(9,25,7,3,'01/04/13','02/05/12','PALAIS OMNISPORT DE PARIS BERCY','Ils se re-aiment');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(10,26,9,5,'07/01/12','02/05/12','OPERA DE VICHY','Les chevaliers du fiel');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(10,27,7,3,'08/04/12','02/05/12','PALAIS OMNISPORT DE PARIS BERCY','Les chevaliers du fiel');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(11,28,4,2,'07/01/12','05/05/12','AXONE','Voca people');
INSERT INTO REPRESENTATION(NUM_SPECT,NUM_REPRESENTATION,NUM_CONFIG,NUM_SALLE,DATE_REPRESENTATION,DATE_OUVERTURE_RESERVATION,NOM_SALLE,NOM_SPECTACLE) 
VALUES(11,29,1,1,'10/24/12','05/05/12','HOTEL CASINO BARRIERE','Voca people');

-- -----------------------------------------------------------------------------
--       TABLE : TARIFER
-- -----------------------------------------------------------------------------

INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,1,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,2,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,3,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,4,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CARRE OR','NORMAL',56.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT1','NORMAL',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT2','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT1','REDUIT',41.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(1,5,'CAT2','REDUIT',34.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,6,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,7,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,8,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT1','NORMAL',130.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CARRE OR','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT2','NORMAL',95.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(2,9,'CAT3','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,10,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,10,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,11,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,11,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,12,'CAT3','NORMAL',43.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,13,'CAT1','NORMAL',65.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(3,13,'CAT2','NORMAL',54.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT1','NORMAL',122.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CARRE OR','NORMAL',100.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT2','NORMAL',72.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,14,'CAT3','NORMAL',50.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT1','NORMAL',122.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CARRE OR','NORMAL',100.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT2','NORMAL',72.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(4,15,'CAT3','NORMAL',50.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT1','NORMAL',69.70);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT2','NORMAL',59.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,16,'CAT3','NORMAL',49.90);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT1','NORMAL',69.70);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT2','NORMAL',59.80);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(5,17,'CAT3','NORMAL',49.90);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,18,'CAT1','NORMAL',76.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,18,'CAT2','NORMAL',65.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT1','NORMAL',76.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT2','NORMAL',65.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT1','SPECIAL',66.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(6,19,'CAT2','SPECIAL',55.30);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT1','NORMAL',59.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CARRE OR','NORMAL',80.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,20,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,21,'CAT1','NORMAL',59.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(7,21,'CARRE OR','NORMAL',80.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CARRE OR','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','NORMAL',65.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','PROMOTION WEB',51.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','PROMOTION WEB',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','PROMOTION WEB',30.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT1','FAMILLE',45.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT2','FAMILLE',33.75);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,22,'CAT3','FAMILLE',23.75);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CARRE OR','NORMAL',75.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT1','NORMAL',65.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(8,23,'CAT3','NORMAL',39.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,24,'CAT1','NORMAL',55.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,24,'CAT2','NORMAL',49.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT1','NORMAL',58.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT2','NORMAL',48.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(9,25,'CAT3','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,26,'UNIQUE','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,27,'CARRE OR','NORMAL',38.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(10,27,'CAT1','NORMAL',30.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CARRE OR','NORMAL',44.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT1','NORMAL',38.50);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT2','NORMAL',33.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CARRE OR','GROUPE',39.60);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT1','GROUPE',35.20);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,28,'CAT2','GROUPE',28.60);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,29,'CAT1','NORMAL',44.00);
INSERT INTO TARIFER(NUM_SPECT,NUM_REPRESENTATION,LIB_CAT,LIB_CAT_SPECT,PRIX) 
VALUES(11,29,'CAT2','NORMAL',40.00);

-- -----------------------------------------------------------------------------
--       TABLE : RESERVATION
-- -----------------------------------------------------------------------------

INSERT INTO RESERVATION(NUM_RESERVATION,EMAIL_CLIENT,DATE_RESERVATION,
	MONTANT_FACTURE,NUM_TRANSACTION,DATE_TRANSACTION) VALUES();

-- -----------------------------------------------------------------------------
--       TABLE : POSITION
-- -----------------------------------------------------------------------------

INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Gradins',0,950);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Mezzanine',0,100);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(1,'Balcon',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Gradins',0,1000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Tribunes',0,500);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(2,'Parterre',3500,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(3,'Gradins',0,14000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(3,'Fosse',4000,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(4,'Gradins',0,15000);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(4,'Fosse',8000,0);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'2eme Balcon',0,200);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'loges 1er Balcon',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'1er Balcon',0,200);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'loges d''orchestre',0,150);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(5,'Orchestre',0,700);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(6,'Gradins',0,4900);
INSERT INTO POSITION(NUM_SALLE,NOM_POSITION,CAPACITE_DEBOUT,CAPACITE_ASSISE) 
VALUES(6,'Parterre',3600,0);

-- -----------------------------------------------------------------------------
--       TABLE : PLACE_ASSISE
-- -----------------------------------------------------------------------------

INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',004,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',005,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Mezzanine',006,'M','B');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',007,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',008,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(1,'Balcon',009,'B','C');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',004,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',005,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(2,'Tribunes',006,'T','D');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(3,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(4,'Gradins',003,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',001,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',002,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'2eme Balcon',003,'2B','E');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',004,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',005,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'1er Balcon',006,'1B','F');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',007,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',008,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges 1er Balcon',009,'L1B','I');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',010,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',011,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'loges d''orchestre',012,'LO','J');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',013,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',014,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(5,'Orchestre',015,'O','K');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',001,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',002,'G','A');
INSERT INTO PLACE_ASSISE(NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,BLOC) 
VALUES(6,'Gradins',003,'G','A');

-- -----------------------------------------------------------------------------
--       TABLE : BILLET_SPECTACLE
-- -----------------------------------------------------------------------------

INSERT INTO BILLET_SPECTACLE(NUM_SPECT,NUM_REPRESENTATION,NUM_BILLET,NUM_RESERVATION,
	LIB_CAT_SPECT,LIB_CAT,NUM_SALLE,NOM_POSITION,NUM_PLACE,RANG,PRIX) VALUES();

>>>>>>> 853c42bc054614ce2a94670e365d6861123860e1:scripts/300_insert_data.sql
commit;